\documentclass{article}

%\VignetteEngine{knitr::knitr}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

\title{Heterogeneous Clustering and Network Inference with the MixGLasso}

\begin{document}

\maketitle

<<echo=FALSE, include=TRUE>>=
# Load package
#library(nethet)

library(ggplot2)

# For now, load only needed source files
source('../R/simMix.R')
@

\section{Introduction}




\section{Simulate Data}

In order to demonstrate the functionalities of the MixGLasso, we will first simulate data from a Gaussian mixture model with a known covariance structure. The \textit{nethet} package includes code for generating random covariance matrices with a given sparsity, and for simulating from a Gaussian mixture model with given means and covariances. The function \texttt{sim.mix.networks} provides a convenient wrapper for both:

<<echo=TRUE, include=TRUE>>=
# Specify number of simulated samples and dimensionality
n = 100
p = 25

# Specify number of components of the mixture model and mixture probabilities
n.comp = 4
mix.prob = c(0.2, 0.4, 0.3, 0.1)

# Specify sparsity in [0,1], indicating fraction of off-diagonal zero entries.
s = 0.9



# Generate networks with random means and covariances. Means will be drawn from 
# a standard Gaussian distribution, non-zero covariance values from a 
# Beta(1,1) distribution.
sim.result = sim.mix.networks(n, p, 4, s, mix.prob)
@

The data is contained in \texttt{sim.result\$data}, and the components that each 
data point belongs to are contained in \texttt{sim.result\$comp}. Let's check
that the mixture probabilities are correct and then plot the first two 
dimensions of the data. Note that we do not expect these to be well-separated in
any way.

<<echo=TRUE, include=TRUE>>=
print(table(sim.result$comp)/n)

component = as.factor(sim.result$comp)

qplot(x=sim.result$data[,1], y=sim.result$data[,2], 
      colour=component) + 
  xlab('Dimension 1') +
  ylab('Dimension 2')
  
@

The means and covariances of the data are contained in \texttt{sim.result\$Mu} 
and \texttt{sim.result\$Sig}. If desired, they can also be specified when calling
\texttt{sim.mix.networks}.

<<echo=TRUE, include=TRUE>>=
# Generate new dataset with the same covariances, but different means
sim.result.new = sim.mix.networks(n, p, 4, s, mix.prob, Sig=sim.result$Sig)

component = as.factor(sim.result.new$comp)

qplot(x=sim.result.new$data[,1], y=sim.result.new$data[,2], 
      colour=component) + 
  xlab('Dimension 1') +
  ylab('Dimension 2')
@

\section{Clustering}

\section{Network Inference}

Include glasso.

\section{Plotting and Exporting Results}

\subsection{Network Plots}

\subsection{Edge Plots}

Dot plot and scatter plot

\subsection{Exporting Results}


\end{document}